### ISSUE TITLE
Unable to install: Yarn error "No license field"

### ISSUE THREAD

**Issue by mikenotfound** [AnvarNazar/insomnia-plugin-global-headers#1]
Plugin installation fails due to yarn error:

```
Error: Yarn error {"type":"warning","data":"package.json: No license field"}

    at file:///opt/Insomnia/resources/app.asar/bundle.js:117470:16
    at ChildProcess.exithandler (child_process.js:303:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

**Comment by AnvarNazar** [comment]
What version of insomnia are you using.

**Comment by mikenotfound** [comment]
> What version of insomnia are you using.

Thanks for the response @AnvarNazar, here's what I have:

- Insomnia 2021.7.2. 
- Linux x64 5.4.0-88-generic
- Electron 11.2.3
- Node 12.18.3

**Comment by AnvarNazar** [comment]
> > What version of insomnia are you using.
> 
> Thanks for the response @AnvarNazar, here's what I have:
> 
>     * Insomnia 2021.7.2.
> 
>     * Linux x64 5.4.0-88-generic
> 
>     * Electron 11.2.3
> 
>     * Node 12.18.3

I tested this on Insomnia 2021.7.2. Can't reproduce the issue. My electron version 11.5.0
